# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-10 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBSReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RContents', models.TextField(verbose_name='评论内容')),
                ('RMe', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_user.BBSReply', verbose_name='父级评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='BBSSecion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SName', models.CharField(max_length=50, verbose_name='板块名称')),
                ('SStatement', models.CharField(max_length=200, verbose_name='版块说明')),
                ('SClickConut', models.IntegerField(default=0, verbose_name='版块点击次数')),
                ('STopicConut', models.IntegerField(default=0, verbose_name='版块帖子数')),
            ],
            options={
                'verbose_name': '版块',
                'verbose_name_plural': '版块',
            },
        ),
        migrations.CreateModel(
            name='BBSTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TReplyCount', models.IntegerField(default=0, verbose_name='贴子回复次数')),
                ('TTopic', models.CharField(max_length=100, verbose_name='贴子标题')),
                ('TContents', models.TextField(verbose_name='贴子内容')),
                ('TTime', models.DateTimeField(auto_now_add=True, verbose_name='发贴时间')),
                ('TClickCount', models.IntegerField(default=0, verbose_name='贴子点击次数')),
                ('is_delect', models.BooleanField(verbose_name='是否删除')),
                ('TSID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.BBSSecion', verbose_name='贴子板块编号')),
            ],
            options={
                'verbose_name': '贴子',
                'verbose_name_plural': '贴子',
            },
        ),
        migrations.CreateModel(
            name='BBSUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UName', models.CharField(max_length=12, verbose_name='用户名')),
                ('UPassword', models.CharField(max_length=50, verbose_name='用户密码')),
                ('UEmail', models.CharField(max_length=100, verbose_name='Email')),
                ('UBirthady', models.DateTimeField()),
                ('USex', models.CharField(choices=[('男', '1'), ('女', '2'), ('保密', '3')], default='保密', max_length=10, verbose_name='性别')),
                ('UClass', models.IntegerField(default=0, verbose_name='等级')),
                ('UStatement', models.CharField(blank=True, max_length=200, null=True, verbose_name='签名')),
                ('URegDate', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('UPoint', models.IntegerField(default=0, verbose_name='用户积分')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='bbstopic',
            name='Tuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.BBSUsers', verbose_name='贴子用户编号'),
        ),
        migrations.AddField(
            model_name='bbssecion',
            name='SMasterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.BBSUsers', verbose_name='版主id'),
        ),
        migrations.AddField(
            model_name='bbsreply',
            name='RTopicID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.BBSTopic', verbose_name='贴子ID'),
        ),
        migrations.AddField(
            model_name='bbsreply',
            name='RUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.BBSUsers', verbose_name='评论用户id'),
        ),
    ]
